---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci

  stage-binaries:
    image: rancher/dapper:1.11.2
    commands:
    - cp -r ./bin/* ./package/
    when:
      branch: [master, release/*]
      event: [push,tag]

  docker-publish-master:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: cloudnautique/rancher
    context: package/
    tag: master
    secrets: [docker_username, docker_password]
    build_args:
    - VERSION=master
    when:
      branch: master
      event: push

  docker-publish-master-agent:
    image: plugins/docker
    dockerfile: package/Dockerfile.agent
    repo: cloudnautique/rancher-agent
    context: package/
    tag: master
    secrets: [docker_username, docker_password]
    build_args:
    - VERSION=master
    when:
      branch: master
      event: push
